
modLoader="javafml" #mandatory

loaderVersion="[36.1.0,)"

license="Todos los derechos reservados por The Lost of Light"

[[mods]] #mandatory

modId="shadowslave" #mandatory

version="1.0.0.1" #mandatory

displayName="Shadow Slave" #mandatory

authors="CrhistTech" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''Shadow Slave es un mod de Minecraft que introduce nuevas mecánicas de juego, acorde a la novela de Shadow Slave'''

[[dependencies.shadowslave]] #optional
    modId="forge" #mandatory
    
    mandatory=true #mandatory

    versionRange="[54.1.0,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.shadowslave]]
    modId="minecraft"
    
    mandatory=true

    versionRange="[1.21.4,1.22)"
    
    ordering="NONE"
    
    side="BOTH"


